dist: bionic
language: node_js
node_js:
  - node
# Based on: https://medium.com/faun/configuring-travis-ci-for-angular-application-34afee1715f
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - npm run lint
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run e2e -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
